name: Build
on:
  pull_request:
  push:
    tags-ignore: [ '**' ]
    branches: [ '**' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
          cache: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v9
      - name: Verify
        run: |
          make verify
      - name: Test
        run: |
          make test
      - name: Build Binary
        env:
          TAG: ${{ github.ref_name }}
          COMMIT: ${{ github.sha }}
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean --snapshot
      - name: "Integration Test"
        run:
          make integration-test
      - name: Image Build
        uses: docker/build-push-action@v7
        with:
          push: false
          build-args: |
            TAG=unistar-mcp:latest
            COMMIT=${{ github.sha }}
          tags: unistar-mcp:latest
          platforms: "linux/amd64,linux/arm64"
          file: package/Dockerfile
          sbom: true
          provenance: mode=max
